server:
  port: 8080

spring:
  datasource:
    #配置当前要使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/qweb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&autoReconnect=true
    username: root
    password:
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  mvc:
     view:
       prefix: /templates/
       suffix: .ftl

#配置日志
logging:
  #配置日志文件路径
  level:
    org.springfromework.web: info
    javax.sql: info
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log